### ISSUE TITLE
运行就报错了

### ISSUE THREAD

**Issue by laose307** [Martin20150405/OpenCV4AndroidWithCmake#6]
2021-08-15 19:08:08.065 31485-31485/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jiangdg.opencv4android, PID: 31485
    java.lang.RuntimeException: Unable to resume activity {com.jiangdg.opencv4android/com.jiangdg.opencv4android.imgproc.ImageSmoothActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
    ]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4270)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:1896)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity$1.onManagerConnected(ImageSmoothActivity.java:64)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity.onResume(ImageSmoothActivity.java:109)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4260)

**Comment by Martin20150405** [comment]
> com.jiangdg.opencv4android.imgproc.ImageSmoothActivity

能不能不要贴无关日志

**Comment by laose307** [comment]
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:1896)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity$1.onManagerConnected(ImageSmoothActivity.java:64)
        at com.jiangdg.opencv4android.imgproc.ImageSmoothActivity.onResume(ImageSmoothActivity.java:109)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4260)

**Comment by Martin20150405** [comment]
我看这个项目代码里面也没有cvtColor的调用呀，这个error的意思是不是说，你传入的image应该是3或4通道的，而你传入的可能是灰度图或者空mat

另外如果不是运行自带的app导致的异常，请不要在此提问

**Comment by laose307** [comment]
我去，就是你git的项目，项目就是用到图片进行颜色转化

**Comment by Martin20150405** [comment]
> 我去，就是你git的项目，项目就是用到图片进行颜色转化

我觉得可能是你的参数传错了，不过这个项目已经很老了，现在不建议这样引入OpenCV，建议去找个新一点的
